config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users
  root 'statics#index'
  get 'contact', to: 'statics#contact'
  resources :meals

  get 'meals/favmeal/:id', to: 'meals#favmeal', as: 'meal_favmeal'
  get 'users/show', to:'users#show'
  get 'users/edit_meal_parameter', to:'users#edit_meal_parameter'
  get 'users/update_meal_parameter', to:'users#update_meal_parameter'

  match '/search_by_name', to: 'meals#search_by_name', via: 'get'
  match '/search_by_categories', to: 'meals#search_by_categories', via: 'get'

  #routes to MealCarts
  get 'meal_carts/show', to:'meal_carts#show', as: 'meal_carts_show'
  get 'meal_carts/new', to:'meal_carts#new'
  get 'meal_carts/generate', to:'meal_carts#generate'
  get 'meal_carts/choice', to:'meal_carts#choice'
  delete 'meal_carts/reinitiate', to:'meal_carts#reinitiate'
  put 'meal_carts/add_meal/:id', to: 'meal_carts#add_meal', as: 'add_meal'
  delete 'meal_carts/delete_meal/:id', to: 'meal_carts#delete_meal', as: 'delete_meal'

  #routes to ShoppingLists
  get 'shopping_lists/generate', to:'shopping_lists#generate'
  get 'shopping_lists/show', to: 'shopping_lists#show'
  delete 'shopping_lists/delete_ingredient/:id', to: 'shopping_lists#delete_ingredient', as: 'delete_ingredient'
  get 'shopping_lists/add_ingredient/show', to: 'shopping_lists#add_ingredient_show'
  post 'shopping_lists/add_ingredient', to: 'shopping_lists#add_ingredient'
  get 'shopping_lists/add_quantity_per_ingredient/show/:id', to: 'shopping_lists#add_quantity_per_ingredient_show', as: 'shopping_lists_add_quantity_per_ingredient_show'
  post 'shopping_lists/add_quantity_per_ingredient', to: 'shopping_lists#add_quantity_per_ingredient'
  get 'shopping_lists/share', to:'shopping_lists#share'

  #routes user meal historic
  get 'user_meal_historic', to: 'user_meal_histories#show'

  #routes to DatabaseMealsManager (only admin)
  get 'manager/get_meal', to: 'database_meals_manager#get_meal'
  post 'manager/create_meal', to: 'database_meals_manager#create_meal'
  get 'manager/err_meal', to: 'database_meals_manager#err_meal'
  get 'manager/select_meal', to: 'database_meals_manager#select_meal'
  get 'manager/edit_meal_ustensils', to: 'database_meals_manager#edit_meal_ustensils'
  post 'manager/update_meal_ustensils', to: 'database_meals_manager#update_meal_ustensils'
  get 'manager/select_ingredient', to: 'database_meals_manager#select_ingredient'
  get 'manager/edit_ingredient_store_section', to: 'database_meals_manager#edit_ingredient_store_section'
  post 'manager/update_ingredient_store_section', to: 'database_meals_manager#update_ingredient_store_section'
  get 'manager/edit_ingredient_type', to: 'database_meals_manager#edit_ingredient_type'
  post 'manager/update_ingredient_type', to: 'database_meals_manager#update_ingredient_type'
  
end

app/views/renders/_btnBackToTop.html.erb
 <a id="back-to-top" href="#" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left">TOP</a>

app/views/renders/_deviseNotice.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>
  </div>
  </div>
</div>

app/views/renders/_footer.html.erb
<!--footer-->
<div class="animate-footer footer footer-variant-one footer-fluid " id='pied'>
    <div class="container">
        <div class="footer-inner">
            <div class="text-center">
                <%=link_to root_path do%>
            		<%= image_tag('logo2CS.png', alt: "Logo",class:"logo-footer wow animated zoomIn") %>
                <%end%>
            </div>
            <div class="subs-social-options">
                <div class="row custom-row-footer foot-backg">
                    <div class="col-md-6 custom-col-options">
                        <div class="left-side">
                            <div class="widget widget-footer news-letter-signup">
                                <h2 id='title'>Inscrivez vous à la Newsletter:</h2>

                                <form class="subs-form" action="#" method="post">
                                    <div class="email-field">
                                        <input type="email" name="email" placeholder="Enter you email address"/>
                                        <button><i class="fa fa-paper-plane-o"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6" style="height:183px !important;background-color: rgba(0, 0, 0, 0.5) !important ;">
                        <div class="right-side">
                            <div class="widget widget-footer social-icons">
                                <h2 id='title1'>Suivez nous sur les réseaux:</h2>
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                                    <li><a href="#"><i class="fa fa-flickr"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center wow animated flipInY">
                <p>&copy; Copyright 2018 All Rights Reserved by <a href="#">Team MTP !!!</a></p>
            </div>
            <div class="corner-image wow animated fadeInRight">
            	<%= image_tag('footer-corner-image.jpg', alt: "image") %>
            </div>
        </div>
    </div>
</div>
<!--footer ends-->

app/views/renders/_navbar.html.erb
        <!--pre-loader-->
        <div class="preloader">
            <div class="loadr">
                <svg viewbox="0 0 74.6 81">
                    <path d="M67.8,12.9C51.7,5.2,26.2,0.2,26.2,0.2c-10.9-1.8-9.3,11.4-9,20.2c0,0.7,0.1,1.4,0.1,2c7.8,1.5,19.7,4,29.2,7.4c11.4,4.1,9.6,8.3,9.2,16c-0.2,4.9-0.4,14,1.1,21.3c7.7,1.4,13.8,1.9,13.1-0.3c-6.3-7.2-0.1-29.6,1.8-34.2C73.3,28.7,79.3,18.4,67.8,12.9z"></path>
                    <path d="M58.9,79.5c-6.5-5.6-6.2-23.6-5.8-31.3c0.4-7.7,2.1-11.9-9.2-16c-15.3-5.5-37.3-8.8-37.3-8.8c-9.1-1.1-6.6,8.4-5.5,15.1c1.7,10,5.4,22,7.9,27.8c2.8,6.5,8.9,7.3,8.9,7.3S65.4,85.1,58.9,79.5z"></path>
                </svg>
            </div>
        </div>
        <!--pre-loader ends-->        
        <!--header-->
        <header>
            <div class="fade-load-down header header-var2 ext-var4">
                <div class="container">
                    <div class="wrapper-logo-banner">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="logo-wrapper"id='logo'>
                                    <a href="/">
                                        <%= image_tag('logoCS.png', alt: "logo") %>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="banner-login-wrapper">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="wrapper-links">
                                                <ul class="header-social-icons">
                                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                                </ul>


                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </header>
        <!--header ends-->
        <!-- nav-->

        <div class="top-nav"id="navbar">
            <div class="container">
                <nav class="responsive-menu">
                   
                    <ul>
                        
                        <li>
                            <%= link_to 'Nos recettes', meals_path %>
                        </li>

                        <% if user_signed_in? %>
                            <li>
                                <%= link_to "Vos repas !", meal_carts_new_path %>
                            </li>
                            <li>

                                <%= link_to "Votre historique ", user_meal_historic_path %>

                            </li>
                            <li >
                                <%= link_to "Créer votre recette", new_meal_path%>
                            </li>
                            <% if current_user.username == "admin"%>
                            <li>
                                <%= link_to "add recipe from wecook", manager_get_meal_path%>
                            </li>
                            <li>
                                <%= link_to "update meal (ustensils)", manager_select_meal_path%>
                            </li>
                            <li>
                                <%= link_to "update ingredient (store_section & type)", manager_select_ingredient_path%>
                            </li>
                            <% end %>  
                        <% end %>                        
                            <li >                            
                                        <% unless user_signed_in? %>
                                          <li>
                                            <%= link_to "Se connecter", new_user_session_path %>
                                          </li>
                                          <li>
                                          <%= link_to "Creer son compte", new_user_registration_path %>
                                         </li>
                                        <% else %>
                                          <li>
                                            <%= link_to "Mon Profil", users_show_path %>
                                          </li>
                                          <li class="login submit-recipe">
                                            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
                                          </li>
                                        <% end %>
                                
                            </li>
                            <li>
                                <%= link_to 'Contactez-nous', contact_path %>
                            </li>

                    </ul>                       
                </nav>

            </div>
        </div>
        <!-- nav ends-->