config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users
  root 'statics#index'
  get 'contact', to: 'statics#contact'
  resources :meals

  get 'meals/favmeal/:id', to: 'meals#favmeal', as: 'meal_favmeal'
  get 'users/show', to:'users#show'
  get 'users/edit_meal_parameter', to:'users#edit_meal_parameter'
  get 'users/update_meal_parameter', to:'users#update_meal_parameter'

  match '/search_by_name', to: 'meals#search_by_name', via: 'get'
  match '/search_by_categories', to: 'meals#search_by_categories', via: 'get'

  #routes to MealCarts
  get 'meal_carts/show', to:'meal_carts#show', as: 'meal_carts_show'
  get 'meal_carts/new', to:'meal_carts#new'
  get 'meal_carts/generate', to:'meal_carts#generate'
  get 'meal_carts/choice', to:'meal_carts#choice'
  delete 'meal_carts/reinitiate', to:'meal_carts#reinitiate'
  put 'meal_carts/add_meal/:id', to: 'meal_carts#add_meal', as: 'add_meal'
  delete 'meal_carts/delete_meal/:id', to: 'meal_carts#delete_meal', as: 'delete_meal'

  #routes to ShoppingLists
  get 'shopping_lists/generate', to:'shopping_lists#generate'
  get 'shopping_lists/show', to: 'shopping_lists#show'
  delete 'shopping_lists/delete_ingredient/:id', to: 'shopping_lists#delete_ingredient', as: 'delete_ingredient'
  get 'shopping_lists/add_ingredient/show', to: 'shopping_lists#add_ingredient_show'
  post 'shopping_lists/add_ingredient', to: 'shopping_lists#add_ingredient'
  get 'shopping_lists/add_quantity_per_ingredient/show/:id', to: 'shopping_lists#add_quantity_per_ingredient_show', as: 'shopping_lists_add_quantity_per_ingredient_show'
  post 'shopping_lists/add_quantity_per_ingredient', to: 'shopping_lists#add_quantity_per_ingredient'
  get 'shopping_lists/share', to:'shopping_lists#share'

  #routes user meal historic
  get 'user_meal_historic', to: 'user_meal_histories#show'

  #routes to DatabaseMealsManager (only admin)
  get 'manager/get_meal', to: 'database_meals_manager#get_meal'
  post 'manager/create_meal', to: 'database_meals_manager#create_meal'
  get 'manager/err_meal', to: 'database_meals_manager#err_meal'
  get 'manager/select_meal', to: 'database_meals_manager#select_meal'
  get 'manager/edit_meal_ustensils', to: 'database_meals_manager#edit_meal_ustensils'
  post 'manager/update_meal_ustensils', to: 'database_meals_manager#update_meal_ustensils'
  get 'manager/select_ingredient', to: 'database_meals_manager#select_ingredient'
  get 'manager/edit_ingredient_store_section', to: 'database_meals_manager#edit_ingredient_store_section'
  post 'manager/update_ingredient_store_section', to: 'database_meals_manager#update_ingredient_store_section'
  get 'manager/edit_ingredient_type', to: 'database_meals_manager#edit_ingredient_type'
  post 'manager/update_ingredient_type', to: 'database_meals_manager#update_ingredient_type'
  
end

app/models/meal_cart.rb
class MealCart < ApplicationRecord
	#User which created the meal
    belongs_to :user
    #Meals of the meal cart
	has_and_belongs_to_many :meals
end

app/controllers/meal_carts_controller.rb
class MealCartsController < ApplicationController

  def new
    #Delete shopping list
    shopping_list = ShoppingList.find_by(user_id: current_user.id)
    if shopping_list
      shopping_list.delete
    end

    meal_cart = current_user.meal_cart
    if meal_cart.meals.count > 0
      redirect_to meal_carts_choice_path
    else
      max_size = Meal.count
      @cart_max_size = []
      i = 1
      max_size.times do
        @cart_max_size << [i, i]
        i+=1
      end
    end
  end

  def add_meal
    @meal = Meal.find(params[:id])
    current_user_meals = current_user.meal_cart.meals
    current_user_meals << @meal
    redirect_to meals_path
  end

  def delete_meal
    @meal = current_user.meal_cart.meals.find(params[:id])
    current_user.meal_cart.meals.delete(@meal)
    redirect_to meal_carts_show_path
  end

  def choice
  end

  def reinitiate
    @add_to_history_meal = current_user.history_meals
    @meals = current_user.meal_cart.meals
    if @meals
      #add cart meals to user history_meals table before being deleted
      @meals.each do |meal|
        @add_to_history_meal << meal
      end
      #Delete all the meals of the meal_cart
      @meals.delete_all
    end
    redirect_to meal_carts_new_path
  end

  def generate
    meal_number = params[:user_choice][:meal_number].to_i
    meal_cart = current_user.meal_cart

    Meal.all.each do |meal|
      flag_1 = true
      meal.ustensils.each do |ustensil|
        unless current_user.ustensils.include?(ustensil)
          flag_1 = false
        end
      end
      if flag_1 #select meal if user has the need ustensils to prepare it
        meal_ingredient_type = []
        meal.ingredients.each do |ingredient|
          meal_ingredient_type << ingredient.ingredient_type
        end
        flag_2 = true
        current_user.food_restrictions.each do |element|
          if meal_ingredient_type.include?(element)
            flag_2 = false
          end
        end
        if flag_2 #select meal if the meal respect the user's food restrictions
          if meal_cart.meals.count < meal_number
              #add the meal to the meal_cart
              meal_cart.meals << meal
          end
        end

      end
    end

	  redirect_to meal_carts_show_path
  end

  def show
    @meal_cart = current_user.meal_cart
  end

end

app/helpers/meal_carts_helper.rb
module MealCartsHelper
end

app/views/meal_carts/choice.html.erb
<div class="container-user-choice">
  <div class="exist-cart">
	<h2> Accédez à votre liste de repas</h2>
	<%= link_to 'Accéder', meal_carts_show_path, class:"default-btn mid-button theme-color" %>
  </div>
  <div class="restart-cart">

	<h2>Réinitialisez la liste de vos repas</h2>
	<%= link_to 'Réinitialiser', meal_carts_reinitiate_path, method: :delete, data: { confirm: 'Are you sure?' }, class:"default-btn mid-button theme-tag-color" %>

  </div>
</div>

app/views/meal_carts/create.html.erb
<h1>MealCarts#create</h1>
<p>Find me in app/views/meal_carts/create.html.erb</p>

app/views/meal_carts/new.html.erb
<div class="container-cart-new">
  <%= form_tag meal_carts_generate_path, method: :get do %>
  <fieldset>
      <div class="inner-advance-search-cart-new">
        <div class="new-cart-label">
         <%= label_tag "Nombre de repas" %><br><br>
        </div>
          <div class="form-field-cart-new">
            <%= select(:user_choice, :meal_number, @cart_max_size) %><br><br>
          </div><br><br>
          <div class="btn-submit">
          <%= submit_tag "Let's Go !", :name => nil, class:"default-btn mid-button theme-color" %>
          </div>
      </div>
  </fieldset>
  <% end %>
</div>
<br>

app/views/meal_carts/show.html.erb
<!--banner-->
<div class="banner banner-blog">
    <div class="container ">
        <div class="main-heading">
            <h1> Voici votre panier repas </h1>
        </div>
    </div>
</div>
<!--banner ends-->
<div class="recipes-home-body inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9">
        <div class="recipe-set">
            <div class="recipe-listing listing-grid">

              <% @meal_cart.meals.each do |meal| %>
              <div class="listing">
              	<h4>Repas n°<%= meal.id %></h4>
                <div class="image">
                  <a href="#">
                    <%= link_to  meal_path(meal.id) do%>
                        <% if meal.picture_url %>
                            <%= image_tag meal.picture_url %>
                        <% else %>
                            <%= image_tag('listing-1.jpg', alt: "image") %>
                        <% end %>
                    <%end%> 
                  </a>
                </div>

              <div class="detail">
                <h4>
                  <%= link_to meal.name, meal_path(meal.id)%>
                </h4>
                <p>
                    Nam ornare arcu turpis, nec congu Curabitur quis euismod. Nam ornare arcu turpis, nec congu Curabitur quis euismod. Nam ornare gsfg
                </p>
                  <div class="meta-listing">
                    <br>

					          <%= link_to 'retirer', delete_meal_path(meal.id), method: :delete, class:'default-btn mid-button theme-tag-color'%>

                  </div>
                </div>
              </div>
              <% end %>
              <br>


              
            </div class="cart-title">
            <% if @meal_cart.meals.count > 0 %>
                  <%= link_to 'Générer ma liste de courses', shopping_lists_generate_path, class:'default-btn mid-button theme-color' %>
              <% else %>
                  <h3> Votre panier est vide ! </h3>
              <% end %>
              


        </div>
      </div>
    </div>
  </div>
</div>