config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users
  root 'statics#index'
  get 'contact', to: 'statics#contact'
  resources :meals

  get 'meals/favmeal/:id', to: 'meals#favmeal', as: 'meal_favmeal'
  get 'users/show', to:'users#show'
  get 'users/edit_meal_parameter', to:'users#edit_meal_parameter'
  get 'users/update_meal_parameter', to:'users#update_meal_parameter'

  match '/search_by_name', to: 'meals#search_by_name', via: 'get'
  match '/search_by_categories', to: 'meals#search_by_categories', via: 'get'

  #routes to MealCarts
  get 'meal_carts/show', to:'meal_carts#show', as: 'meal_carts_show'
  get 'meal_carts/new', to:'meal_carts#new'
  get 'meal_carts/generate', to:'meal_carts#generate'
  get 'meal_carts/choice', to:'meal_carts#choice'
  delete 'meal_carts/reinitiate', to:'meal_carts#reinitiate'
  put 'meal_carts/add_meal/:id', to: 'meal_carts#add_meal', as: 'add_meal'
  delete 'meal_carts/delete_meal/:id', to: 'meal_carts#delete_meal', as: 'delete_meal'

  #routes to ShoppingLists
  get 'shopping_lists/generate', to:'shopping_lists#generate'
  get 'shopping_lists/show', to: 'shopping_lists#show'
  delete 'shopping_lists/delete_ingredient/:id', to: 'shopping_lists#delete_ingredient', as: 'delete_ingredient'
  get 'shopping_lists/add_ingredient/show', to: 'shopping_lists#add_ingredient_show'
  post 'shopping_lists/add_ingredient', to: 'shopping_lists#add_ingredient'
  get 'shopping_lists/add_quantity_per_ingredient/show/:id', to: 'shopping_lists#add_quantity_per_ingredient_show', as: 'shopping_lists_add_quantity_per_ingredient_show'
  post 'shopping_lists/add_quantity_per_ingredient', to: 'shopping_lists#add_quantity_per_ingredient'
  get 'shopping_lists/share', to:'shopping_lists#share'

  #routes user meal historic
  get 'user_meal_historic', to: 'user_meal_histories#show'

  #routes to DatabaseMealsManager (only admin)
  get 'manager/get_meal', to: 'database_meals_manager#get_meal'
  post 'manager/create_meal', to: 'database_meals_manager#create_meal'
  get 'manager/err_meal', to: 'database_meals_manager#err_meal'
  get 'manager/select_meal', to: 'database_meals_manager#select_meal'
  get 'manager/edit_meal_ustensils', to: 'database_meals_manager#edit_meal_ustensils'
  post 'manager/update_meal_ustensils', to: 'database_meals_manager#update_meal_ustensils'
  get 'manager/select_ingredient', to: 'database_meals_manager#select_ingredient'
  get 'manager/edit_ingredient_store_section', to: 'database_meals_manager#edit_ingredient_store_section'
  post 'manager/update_ingredient_store_section', to: 'database_meals_manager#update_ingredient_store_section'
  get 'manager/edit_ingredient_type', to: 'database_meals_manager#edit_ingredient_type'
  post 'manager/update_ingredient_type', to: 'database_meals_manager#update_ingredient_type'
  
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  # Shopping list have been created by one user
  belongs_to :user
  # Shopping list details (all ingredients and there quantity)
  has_many :shopping_lists_details
  # Shopping list countain many ingredients
  has_many :ingredients, through: :shopping_lists_details
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController

  def generate
  	current_user_meals = current_user.meal_cart.meals
  	shopping_list_user = current_user.shopping_list

		if shopping_list_user != nil # Verification if current_user shopping_list exist
			redirect_to shopping_lists_show_path
		else # Creation of current_user shopping_list
			ShoppingList.create(user_id: current_user.id)
			redirect_to shopping_lists_show_path
		end

		shopping_list = ShoppingList.find_by(user_id: current_user.id)
			current_user_meals.each do |meal|
				meal.ingredients.each do |ingredient|
					@ingredient_detail = Quantity.find_by(meal_id: meal.id, ingredient_id: ingredient.id)
					if (ShoppingListsDetail.find_by(shopping_list_id: shopping_list.id, ingredient_id: ingredient.id)) # ingredient already exist in ShoppingListsDetail
						puts "#"*40
						@detail = ShoppingListsDetail.find_by(shopping_list_id: shopping_list.id, ingredient_id: ingredient.id)
						@new_quantity = @detail.quantity + (@ingredient_detail.quantity * current_user.household)
						puts "hold quantity"
						puts @detail.quantity
						puts "new quantity"
						puts @new_quantity
						@detail.update(quantity: @new_quantity)
					else  # ingredient new in ShoppingListsDetail
						ShoppingListsDetail.create(shopping_list_id: shopping_list.id, ingredient_id: ingredient.id, quantity: (@ingredient_detail.quantity * current_user.household))
					end
				end
			end
  end

  def show
		@shopping_list = ShoppingList.find_by(user_id: current_user.id)
		@list_id = @shopping_list.id
		@user = current_user
		#creating a shopping_list order by store {store => {name => [quantity_type, quantity]}}
		@list_by_store = {}
		@shopping_list.shopping_lists_details.each do |ingredient_detail|
			#ingredient details
			ingredient = Ingredient.find(ingredient_detail.ingredient_id)
			name = ingredient.name
			quantity = ingredient_detail.quantity
			quantity_type = ingredient.quantity_type.name
			stor_section = ingredient.store_section.name

			if @list_by_store[stor_section]
				@list_by_store[stor_section][name] = [quantity_type,quantity]
			else
				@list_by_store[stor_section] = {}
				@list_by_store[stor_section][name] = [quantity_type,quantity]
			end
		end
  end

  def delete_ingredient
    shopping_list = ShoppingList.find_by(user_id: current_user.id)

    # Delete ingredient in shopping_list
    @ingredient = shopping_list.ingredients.find(params[:id])
    shopping_list.ingredients.delete(@ingredient)

    redirect_to shopping_lists_show_path
  end

  def add_ingredient_show
    # Show all ingredients in dropdown
  	@ingredients = Ingredient.all
  end

  def add_ingredient
  	shopping_list = current_user.shopping_list

  	ingredient_to_add = Ingredient.find(params[:ingredient][:ingredient_id])
    #shopping_list.ingredients << @ingredient_add

  	redirect_to shopping_lists_add_quantity_per_ingredient_show_path(ingredient_to_add.id)
  end

	def add_quantity_per_ingredient_show
		ingredient_to_add_id = params[:id]
		@ingredient_to_add = Ingredient.find(ingredient_to_add_id)
    shopping_list = ShoppingList.find_by(user_id: current_user.id)

    # Show quantity_type
    @quantity_type = @ingredient_to_add.quantity_type
  end

	def add_quantity_per_ingredient
		puts "#"*20
		puts params[:quantity]
    shopping_list = ShoppingList.find_by(user_id: current_user.id)

    # Update of the new_quantity
		@new_ingredient_quantity = params[:quantity]
		@ingredient_to_add = Ingredient.find(params[:ingredient_id])
		shopping_list = current_user.shopping_list

		if @new_ingredient_quantity
			shopping_lists_detail = ShoppingListsDetail.find_by(shopping_list_id: shopping_list.id, ingredient_id: @ingredient_to_add.id)
			if shopping_lists_detail
				shopping_lists_detail.update(quantity: @new_ingredient_quantity)
			else
				shopping_list.ingredients << @ingredient_to_add
				shopping_lists_detail = ShoppingListsDetail.find_by(shopping_list_id: shopping_list.id, ingredient_id: @ingredient_to_add.id)
				shopping_lists_detail.update(quantity: @new_ingredient_quantity)
			end
      redirect_to shopping_lists_show_path
    else
      redirect_to shopping_lists_show_path
    end
  end

	def share
		shopping_list = ShoppingList.find_by(user_id: current_user.id)
		#send shopping list by email
		ContactMailer.shop_list(shopping_list, current_user).deliver_now

    redirect_to shopping_lists_show_path
  end

end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/shopping_lists/add_ingredient_show.html.erb
<br>
<div class="container" style="overflow-x:auto;display: flex;justify-content: center;">
	<table style="border: 1px black solid; box-sizing: border-box;box-shadow: 0px 2px 18px 0px rgba(0,0,0,0.5); cursor: pointer; ">
  		<thead>
  			<tr>
  				<th colspan="2" style="text-align: center;background-color: green;color: white;">Ajout d'ingrédients</th>
  			</tr>
  			<tr>
  				<th style="border: 1px black solid; padding-left: 5px; padding-right: 5px;text-align: center;">Ingrédients</th>
  				<th style="border: 1px black solid; padding-left: 5px; padding-right: 5px;text-align: center;">Ajout</th>
  			</tr>
  		</thead>
  		<tbody>
  				<tr>
					<td  style="border: 1px black solid; padding-left: 5px; padding-right: 5px; text-align: center;">
						<%= form_for :ingredient, url: {action: "add_ingredient"} do |f| %>
			              <%= f.collection_select :ingredient_id, @ingredients.order(:name),:id,:name, {include_blank: false}, {class: "form-control"} %>
					</td>
					<td  style="border: 1px black solid; padding-left: 5px; padding-right: 5px;padding-top: 5px;padding-bottom: 5px; text-align: center; color: white;">
						<button type="submit" class="default-btn mid-button theme-color">Ajouter</button>
					</td>
					<% end %>
		</tbody>
    </table>
</div>
<br>

app/views/shopping_lists/add_quantity_per_ingredient_show.html.erb
<br>
<div class="container" style="overflow-x:auto;display: flex;justify-content: center;">
	<table style="border: 1px black solid; box-sizing: border-box;box-shadow: 0px 2px 18px 0px rgba(0,0,0,0.5); cursor: pointer;">
  		<thead>
  			<tr>
  				<th colspan="2" style="text-align: center;background-color: green;color: white;">Choix de la quantité pour <%= @ingredient_to_add.name %></th>
  			</tr>
  			<tr>
  				<th style="border: 1px black solid; padding-left: 5px; padding-right: 5px;text-align: center;">Quantité</th>
  				<th style="border: 1px black solid; padding-left: 5px; padding-right: 5px;text-align: center;">Unité</th>
  			</tr>
  		</thead>
  		<tbody>
					<%= form_tag(shopping_lists_add_quantity_per_ingredient_path(:ingredient_id => @ingredient_to_add.id), method: :post) do %>
						<tr>
							<td  style="border: 1px black solid; padding-left: 5px; padding-right: 5px; text-align: center;">
									<div class="edit-ustensils">
										<%= number_field_tag :quantity %>
									</div>
									<br>
							</td>
							<td  style="border: 1px black solid; padding-left: 5px; padding-right: 5px;padding-top: 5px;padding-bottom: 5px; text-align: center;">
								<%= @quantity_type.name %>
							</td>
					</tr>
					<tr>
						<td  colspan="2" style="border: 1px black solid; padding-left: 5px; padding-right: 5px;padding-top: 5px;padding-bottom: 5px; text-align: center; color: white;">
							<button type="submit" class="default-btn mid-button theme-color">VALIDER</button>
						</td>
					</tr>
				<% end %>
		  </tbody>
    </table>
</div>
    <br>

app/views/shopping_lists/generate.html.erb
<h1>ShoppingLists#generate</h1>
<p>Find me in app/views/shopping_lists/generate.html.erb</p>

app/views/shopping_lists/show.html.erb
<div class="shopping-list-container">
	<h1>Shopping liste n°<%= @list_id %></h1>
		<div>
			<%= link_to 'Ajouter Ingredients', shopping_lists_add_ingredient_show_path, class:'default-btn mid-button theme-color' %>
			<%= link_to 'Envoyer la liste par email', shopping_lists_share_path, class:'default-btn mid-button dark-color'%>
		</div>
		<div class="shopping-list-content">
		<% @list_by_store.each do |store, ingredient_details| %>
			<div class="shopping-list-table">
			<table>
				<thead>
					<tr>
						<th colspan="4" class="table-title">Rayons : <%= store %></th>
					</tr>
					<tr>
						<th class="table-subtitle">Ingredients</th>
						<th class="table-subtitle">Quantités</th>
						<th class="table-subtitle">Unités</th>
						<th class="table-subtitle">Action</th>
					</tr>
				</thead>
				<tbody>
					<% ingredient_details.each do |name, quantity_detail| %>
					<div>
						<tr>
							<td class="list-ingredient-name">- <%= name %></td>
							<td class="list-ingredient-detail"><%= quantity_detail[1] %></td>
							<td class="list-ingredient-detail"><%= quantity_detail[0] %></td>
							<td style="border: 1px black solid; padding-left: 5px; padding-right: 5px; padding-top: 5px; padding-bottom: 5px; text-align: center;"><%= link_to 'retirer', delete_ingredient_path(Ingredient.find_by(name: name).id), method: :delete, class:'default-btn mid-button theme-tag-color'%></td>
						</tr>
					</div>	
					<% end %>
				</tbody>
			</table>
		</div>
		<% end %>
</div>